# Generated by Django 4.2.3 on 2023-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resetpassword_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
