# Generated by Django 4.2.1 on 2023-06-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Trainer'), (3, 'Client')], default=3),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='token',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
