# Generated by Django 4.2.1 on 2023-07-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('admin', 'Admin'), ('trainer', 'Trainer'), ('client', 'Client')], default='client'),
        ),
    ]
