# Generated by Django 4.2.3 on 2023-07-13 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
