# Generated by Django 4.2.3 on 2023-07-13 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('core', '0009_user_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trainer',
        ),
        migrations.AddField(
            model_name='user',
            name='my_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school', to='schools.school'),
        ),
    ]
