# Generated by Django 4.2.3 on 2023-07-13 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('core', '0010_remove_user_trainer_user_my_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_trainer',
        ),
        migrations.AddField(
            model_name='user',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school', to='schools.school'),
        ),
    ]
