# Generated by Django 4.2.3 on 2023-07-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_completed_report_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='visible_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
