# Generated by Django 4.2.3 on 2023-07-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
